### ISSUE TITLE
NPM package returning not found for version 3.1.0

### ISSUE THREAD

**Issue by r0qs** [OpenZeppelin/openzeppelin-contracts#2321]
Hi, it seems that the last npm package update it's broken.

**💻 Environment**

npm@6.14.7
node@v14.7.0

**📝 Details**

```
2721 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@openzeppelin%2fcontracts - Not found
2721 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:114:15
2721 verbose stack     at runMicrotasks (<anonymous>)
2721 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2722 verbose statusCode 404
2723 verbose pkgid @openzeppelin/contracts@^3.1.0
2724 verbose cwd /home/cromagnon/ctdapp/
2725 verbose Linux 5.6.15-arch1-1
2726 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
2727 verbose node v14.7.0
2728 verbose npm  v6.14.7
2729 error code E404
2730 error 404 Not Found - GET https://registry.npmjs.org/@openzeppelin%2fcontracts - Not found
2731 error 404
2732 error 404 '@openzeppelin/contracts@^3.1.0' is not in the npm registry.
```

**To reproduce**
Just try to run: `npm install @openzeppelin/contracts`

I suspect that the encode of the url is wrong.

**Comment by r0qs** [comment]
Ops, I just find out that it seems to be an issue in the NPM registry: https://github.com/npm/cli/issues/1628 and https://github.com/npm/cli/issues/1624.

Sorry.
