### ISSUE TITLE
Failed To use truffle-flattener on RC721PresetMinterPauserAutoId.sol

### ISSUE THREAD

**Issue by GuillaumeBraux** [OpenZeppelin/openzeppelin-contracts#2657]
Hello, I try to use truffle-flattener on the RC721PresetMinterPauserAutoId.sol but this error came out

truffle-flattener contracts/openzeppelin-contracts/contracts/token/ERC721/presets/ERC721PresetMinterPauserAutoId.sol
Error: Could not parse contracts/openzeppelin-contracts/contracts/utils/Counters.sol for extracting its imports: ParserError: missing ';' at '{' (26:18)
    at getDependencies (/usr/local/lib/node_modules/truffle-flattener/index.js:44:11)
    at dependenciesDfs (/usr/local/lib/node_modules/truffle-flattener/index.js:64:24)
    at async dependenciesDfs (/usr/local/lib/node_modules/truffle-flattener/index.js:73:7)
    at async getSortedFilePaths (/usr/local/lib/node_modules/truffle-flattener/index.js:83:5)
    at async flatten (/usr/local/lib/node_modules/truffle-flattener/index.js:180:23)
    at async main (/usr/local/lib/node_modules/truffle-flattener/index.js:237:3)

**Comment by frangio** [comment]
This is because `truffle-flattener` does not support the `unchecked` blocks in Solidity 0.8. Please report over at [nomiclabs/truffle-flattener](https://github.com/nomiclabs/truffle-flattener/).
