### ISSUE TITLE
Upgradeable contract on VeChain

### ISSUE THREAD

**Issue by mastercodingbear** [OpenZeppelin/openzeppelin-contracts#3217]
**💻 Environment**
```
Truffle v5.5.0 (core: 5.5.0)
Ganache v7.0.1
Solidity - 0.8.11 (solc-js)
Node v14.18.2
Web3.js v1.5.3
```

**📝 Details**

```
Error: Method not found
    at Object.send (F:\projects\ExoWorlds\node_modules\@openzeppelin\truffle-upgrades\src\utils\wrap-provider.ts:18:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at getChainId (F:\projects\ExoWorlds\node_modules\@openzeppelin\upgrades-core\src\provider.ts:34:14)
    at Function.forNetwork (F:\projects\ExoWorlds\node_modules\@openzeppelin\upgrades-core\src\manifest.ts:46:25)
    at deployProxy (F:\projects\ExoWorlds\node_modules\@openzeppelin\truffle-upgrades\src\deploy-proxy.ts:40:20)
    at module.exports (F:\projects\ExoWorlds\migrations\3_deploy_upgradeable_contracts.js:15:5)
    at Migration._deploy (C:\Users\ggg\AppData\Roaming\nvm\v14.18.2\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:72:1)
    at Migration._load (C:\Users\ggg\AppData\Roaming\nvm\v14.18.2\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:54:1)
    at Migration.run (C:\Users\ggg\AppData\Roaming\nvm\v14.18.2\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:202:1)
    at Object.runMigrations (C:\Users\ggg\AppData\Roaming\nvm\v14.18.2\node_modules\truffle\build\webpack:\packages\migrate\index.js:152:1)
    at Object.runFrom (C:\Users\ggg\AppData\Roaming\nvm\v14.18.2\node_modules\truffle\build\webpack:\packages\migrate\index.js:117:1)
    at Object.run (C:\Users\ggg\AppData\Roaming\nvm\v14.18.2\node_modules\truffle\build\webpack:\packages\migrate\index.js:94:1)
    at runMigrations (C:\Users\ggg\AppData\Roaming\nvm\v14.18.2\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate\run.js:78:1)
    at Object.module.exports [as run] (C:\Users\ggg\AppData\Roaming\nvm\v14.18.2\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate\run.js:44:1)
    at Command.run (C:\Users\ggg\AppData\Roaming\nvm\v14.18.2\node_modules\truffle\build\webpack:\packages\core\lib\command.js:189:1)
Truffle v5.5.0 (core: 5.5.0)
Node v14.18.2
```

**🔢 Code to reproduce bug**
Contract using with Truffle. [Tutorial](https://docs.openzeppelin.com/upgrades-plugins/1.x/truffle-upgrades)

Is this bug due to VeChain or Openzeppelin?

**Comment by frangio** [comment]
Sounds like it's VeChain. You should check if the RPC node suports `eth_chainId`. 

Otherwise open an issue in https://github.com/OpenZeppelin/openzeppelin-upgrades.
