### ISSUE TITLE
Update to latest `merkletreejs` version will break a unit test in `MerkleProof.test.js`

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/openzeppelin-contracts#3813]
I just wanted to let you know that if you update to the latest `merkletreejs` version (`0.3.2`), the following [line]( https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/test/utils/cryptography/MerkleProof.test.js#L49) will break (at least it did for me :-D):
```js
const badProof = badMerkleTree.getHexProof(badElements[0]);
```

I realised it since I used the same test setup for my Vyper Snekmake foundry tests. You can fix it by adding the index of `2`. See my commit here: https://github.com/pcaversaccio/snekmate/commit/0f66c3eabbd5e5a8865eab057084749ce1d6c48d:
```js
const badProof = badMerkleTree.getHexProof(badElements[0], 2);
// or the following will produce the same result as well
const badProof = badMerkleTree.getHexProof(badElements[2], 2);
```

**Comment by pcaversaccio** [comment]
Tbh I didn't do a deep-dive since there are no release notes which pisses me somehow off. I think that PR introduced the change: https://github.com/merkletreejs/merkletreejs/commit/cf066ac963a6094bbce1ab2c01b9529d8d12b7c1. 

the difference would be the following:

```diff
+ getHexProofs ():string[] {
+   return this.getProofs().map(item => this.bufferToHex(item.data))
+}

- getHexProof (leaf: Buffer | string, index?: number):string[] {
-   return this.getProof(leaf, index).map(item => this.bufferToHex(item.data))
- }
```

Cc: @miguelmota

**Comment by pcaversaccio** [comment]
For the error logs, you can see a failed action [here](https://github.com/pcaversaccio/snekmate/actions/runs/3457987397/jobs/5771954704):

```bash
2022-11-14T02:10:50.649702Z ERROR foundry_evm::executor::inspector::cheatcodes::ext: stderr err="/home/runner/work/snekmate/snekmate/node_modules/@ethersproject/logger/lib/index.js:247\n        throw this.makeError(message, code, params);\n        ^\n\nError: types/values length mismatch (count={\"types\":1,\"values\":2}, value={\"types\":[\"bytes32\"],\"values\":[\"0x\",\"0x\"]}, code=INVALID_ARGUMENT, version=abi/5.7.0)\n    at Logger.makeError (/home/runner/work/snekmate/snekmate/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/home/runner/work/snekmate/snekmate/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at AbiCoder.encode (/home/runner/work/snekmate/snekmate/node_modules/@ethersproject/abi/lib/abi-coder.js:83:20)\n    at Object.<anonymous> (/home/runner/work/snekmate/snekmate/test/utils/scripts/generate-bad-proof.js:11:32)\n    at Module._compile (node:internal/modules/cjs/loader:1155:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)\n    at Module.load (node:internal/modules/cjs/loader:1033:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:868:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:22:47 {\n  reason: 'types/values length mismatch',\n  code: 'INVALID_ARGUMENT',\n  count: { types: 1, values: 2 },\n  value: { types: [ 'bytes32' ], values: [ '0x', '0x' ] }\n}\n"
```

**Comment by pcaversaccio** [comment]
I actually just realised that the latest version `0.3.2` is not even committed to the repo as the latest version bump is to `0.3.1`. https://github.com/merkletreejs/merkletreejs/commit/68566c5ae9d3638f7467f8ac944f342973b35f7d.

**Comment by miguelmota** [comment]
Can you provide a reproducible snippet? there hasn't been any functional changes; only addition of new methods and updated return type as you pointed out in commit, any all the lib tests still pass, so I wouldn't expect there to be any breaking changes but I could be missing something

**Comment by pcaversaccio** [comment]
sure - the following snippet will run with version `0.3.0` but not with `0.3.2`:

```js
const { MerkleTree } = require("merkletreejs");
const ethers = require("ethers");

const badElements = ["d", "e", "f"];
const badMerkleTree = new MerkleTree(badElements);

const badProof = badMerkleTree.getHexProof(badElements[0]);

// eslint-disable-next-line no-undef
process.stdout.write(
  ethers.utils.defaultAbiCoder.encode(["bytes32"], badProof)
);
```

**Comment by miguelmota** [comment]
Thanks @pcaversaccio. The latest version should be fixed now. There were some optimization updates recently but the tests didn't catch that there was a breaking change so it's been updated now to undo the line that caused the breaking change.

**Comment by miguelmota** [comment]
As frangio pointed out, the oz lib `@openzeppelin/merkle-tree` will supersede merkletreejs since it'll be more well maintained in the longer term

**Comment by pcaversaccio** [comment]
@miguelmota awesome - just upgraded and can confirm it runs smoothly. Ok, I will upgrade my Merkle proof verification tests to `@openzeppelin/merkle-tree` once my time permits. Closing the issue now as it's resolved.
