### ISSUE TITLE
Contract `_contract` is not upgrade safe. Implementation is missing a public `upgradeTo(address)` function

### ISSUE THREAD

**Issue by quiet-node** [OpenZeppelin/openzeppelin-contracts#4712]
So I have updated @Openzeppelin/contracts-upgradable from v4.x to the latest v.5.0.0, and when I try to deploy a proxy contract, I got this error

```bash
 Error: Contract `contracts/proxy-upgrade/exchange/Exchange.sol:Exchange` is not upgrade safe

contracts/proxy-upgrade/exchange/Exchange.sol:12: Implementation is missing a public `upgradeTo(address)` function
Inherit UUPSUpgradeable to include this function in your contract
@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol
https://zpl.in/upgrades/error-008
  at assertUpgradeSafe (node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:19:11)
  at validateImpl (node_modules/@openzeppelin/hardhat-upgrades/src/utils/validate-impl.ts:42:20)
  at validateProxyImpl (node_modules/@openzeppelin/hardhat-upgrades/src/utils/validate-impl.ts:63:10)
  at deployProxyImpl (node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:73:3)
  at Proxy.deployProxy (node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:45:28)
  at deployDEXProxyContract (test/proxy-upgrade/proxyUpgradeContracts.js:75:21)
  at Context.<anonymous> (test/proxy-upgrade/proxyUpgradeContracts.js:55:23)
```

Here is my setup: 

My `Exchange` contract has already inherited from the `@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol` like below:
```solidity
import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";

contract Exchange is UUPSUpgradeable, OwnableUpgradeable {
...
}
```

Here is how I deploy it in my unit test: (Hardhat + Ethersjs + javascript)
```javascript
const { ethers, upgrades } = require('hardhat')
async function deployDEXProxyContract(token) {
      const contract = await ethers.getContractFactory(
        Constants.Contract.Exchange
      )

      const proxy = await upgrades.deployProxy(contract, [token], {
        kind: 'uups',
        initializer: 'initialize',
      })

      await proxy.deployed()

      return proxy
    }
```

I've noticed that in this [PR](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4382), the `upgradeTo` method has been removed from the UUPSUpgradable contract. Additionally, in this [FAQ question](https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#why-public-upgradeto), it states that I need either `upgradeTo` or `upgradeToAndCall`. While `upgradeToAndCall` is still available in the `UUPSUpgradable`, I'm encountering an error. 

Is this a potential bug or something else?"

**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by ernestognw** [comment]
Support for implementations with either `upgradeTo` or `upgradeToAndCall` was added in [this PR](https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/880) and was [released in `@openzeppelin/upgrades-core@1.29.0`](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fupgrades-core%401.29.0).

Consider upgrading your `@openzeppelin/hardhat-upgrades` version to the [`@2.3.0` release](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%402.3.0) or above.

Can you confirm it actually solves it? I guess we can close this if so

**Comment by quiet-node** [comment]
Hello @ernestognw, thanks for the comment! So I currently have `"@openzeppelin/hardhat-upgrades": "^1.22.1",` Now when I try to upgrade it to `"@openzeppelin/hardhat-upgrades": "^2.3.0",` I get 

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @hashgraph/smart-contracts@0.6.0-SNAPSHOT
npm ERR! Found: @openzeppelin/hardhat-upgrades@1.28.0
npm ERR! node_modules/@openzeppelin/hardhat-upgrades
npm ERR!   dev @openzeppelin/hardhat-upgrades@"^2.3.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @openzeppelin/hardhat-upgrades@"^2.3.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: ethers@6.8.0
npm ERR! node_modules/ethers
npm ERR!   peer ethers@"^6.6.0" from @openzeppelin/hardhat-upgrades@2.3.3
npm ERR!   node_modules/@openzeppelin/hardhat-upgrades
npm ERR!     dev @openzeppelin/hardhat-upgrades@"^2.3.0" from the root project
```

Our codebase currently is using ethers@v5.x. Do you know if there is another approach for this?
